# Shell variables
# Generated by 'wal'
wallpaper='/home/andrew/Photos/wallpapers/bottomless_pit_fanart.jpg'

# Special
background='#070708'
foreground='#cee0f4'
cursor='#cee0f4'

# Colors
color0='#070708'
color1='#64A4EA'
color2='#DCA2BE'
color3='#EAD290'
color4='#FDF28E'
color5='#FDFCB2'
color6='#97B0F0'
color7='#cee0f4'
color8='#909caa'
color9='#64A4EA'
color10='#DCA2BE'
color11='#EAD290'
color12='#FDF28E'
color13='#FDFCB2'
color14='#97B0F0'
color15='#cee0f4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
