# Shell variables
# Generated by 'wal'
wallpaper='/home/andrew/Photos/wallpapers/death_grips_4_black_dice.png'

# Special
background='#07100E'
foreground='#d496d9'
cursor='#d496d9'

# Colors
color0='#07100E'
color1='#A73F4B'
color2='#96525F'
color3='#099C6A'
color4='#9B8A75'
color5='#6C5D98'
color6='#9A6C99'
color7='#d496d9'
color8='#946997'
color9='#A73F4B'
color10='#96525F'
color11='#099C6A'
color12='#9B8A75'
color13='#6C5D98'
color14='#9A6C99'
color15='#d496d9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
