#!/usr/bin/env sh

hide_inactive=0

playing=
paused=
stopped=

if [ -n "$BLOCK_INSTANCE" ]; then
  player="$BLOCK_INSTANCE"
else
  player=$(playerctl -l | head -n1)
fi

while getopts p:a:b:c:q opt; do
  case "$opt" in
    p) player="$OPTARG" ;;
    a) playing="$OPTARG" ;;
    b) paused="$OPTARG" ;;
    c) stopped="$OPTARG" ;;
    q) hide_inactive=1 ;;
  esac
done


artist=$(playerctl -p "$player" metadata artist)
title=$(playerctl -p "$player" metadata title)
status=$(playerctl -p "$player" status)

if [ $? -ne 0 ];then
  exit 1
fi

case "$status" in
  Playing) status_name="$playing" ;;
  Paused) status_name="$paused" ;;
  Stopped) status_name="$stopped" ;;
esac


case "$BLOCK_BUTTON" in
  1|4) playerctl -p "$player" next ;;
  3|5) playerctl -p "$player" previous ;;
  2) playerctl -p "$player" play-pause ;;
esac


if [ $hide_inactive -eq 1 -a "$status" = Stopped ]; then
  exit 0
fi


printf "%s - %s %s\n" "$artist" "$title" "$status_name"
printf "\n"
